var harryPotter = {
	name: 'Harry Potter',
	array: ['BlaiseZabini', 'CorbanYaxley', 'OliverWood', 'RonWeasley', 'PercyWeasley',
'MollyWeasley', 'GinnyWeasley', 'GeorgeWeasley', 'FredWeasley',
'CharlieWeasley', 'BillWeasley', 'ArthurWeasley', 'MyrtleWarren',
'LordVoldemort', 'SeptimaVector', 'RomildaVane', 'EmmelineVance',
'DoloresJane Umbridge', 'WilkieTwycross', 'SybillTrelawney', 'Travers',
'TedTonks', 'NymphadoraTonks', 'AndromedaTonks', 'DeanThomas', 'PiusThicknesse',
'PomonaSprout', 'AliciaSpinnet', 'SeverusSnape', 'ZachariasSmith',
'HepzibahSmith', 'SalazarSlytherin', 'HoraceSlughorn', 'RitaSkeeter',
'AuroraSinistra', 'StanShunpike', 'KingsleyShacklebolt', 'RufusScrimgeour',
'NewtScamander', 'AlbertRuncorn', 'ThorfinnRowle', 'AugustusRookwood',
'DemelzaRobins', 'TomMarvolo Riddle', 'RowenaRavenclaw', 'HelenaRavenclaw',
'QuirinusQuirrell', 'LilyPotter', 'JamesPotter', 'HarryPotter', 'PoppyPomfrey',
'SturgisPodmore', 'IrmaPince', 'IgnotusPeverell', 'CadmusPeverell',
'AntiochPeverell', 'PeterPettigrew', 'ParvatiPatil', 'PadmaPatil',
'PansyParkinson', 'GarrickOllivander', 'BobOgden', 'TheodoreNott',
'AlastorMoody', 'GrahamMontague', 'CormacMcLaggen', 'MinervaMcGonagall',
'ErnieMacmillan', 'OlympeMaxime', 'GriseldaMarchbanks', 'MadamMalkin',
'NarcissaMalfoy', 'LuciusMalfoy', 'DracoMalfoy', 'WaldenMacnair', 'RemusLupin',
'XenophiliusLovegood', 'LunaLovegood', 'NevilleLongbottom', 'FrankLongbottom',
'AugustaLongbottom', 'AliceLongbottom', 'GilderoyLockhart',
'RodolphusLestrange', 'RabastanLestrange', 'BellatrixLestrange',
'SilvanusKettleburn', 'ViktorKrum', 'IgorKarkaroff', 'BerthaJorkins',
'LeeJordan', 'AngelinaJohnson', 'MafaldaHopkirk', 'RolandaHooch',
'RubeusHagrid', 'GodricGryffindor', 'WilhelminaGrubbly-Plank',
'GellertGrindelwald', 'FenrirGreyback', 'Gregorovitch', 'HermioneGranger',
'GregoryGoyle', 'GoyleSr', 'AnthonyGoldstein', 'MorfinGaunt', 'MeropeGaunt',
'MarvoloGaunt', 'CorneliusFudge', 'FloreanFortescue', 'FiliusFlitwick',
'MundungusFletcher', 'MarcusFlint', 'SeamusFinnigan', 'JustinFinch-Fletchley',
'ArgusFilch', 'ArabellaFigg', 'MariettaEdgecombe', 'VernonDursley',
'PetuniaDursley', 'MarjorieDursley', 'DudleyDursley', 'AlbusDumbledore',
'AberforthDumbledore', 'AntoninDolohov', 'ElphiasDoge', 'CedricDiggory',
'AmosDiggory', 'DedalusDiggle', 'GabrielleDelacour', 'FleurDelacour', 'Dawlish',
'RogerDavies', 'Bartemius Crouch Jr', 'Bartemius Crouch Sr', 'DirkCresswell',
'DennisCreevey ', 'ColinCreevey ', 'VincentCrabbe Sr', 'VincentCrabbe',
'MichaelCorner ', 'Mrs.Cole', 'PenelopeClearwater ', 'ChoChang ',
'MaryCattermole ', 'ReginaldCattermole ', 'AmycusCarrow ', 'AlectoCarrow ',
'FrankBryce ', 'CharityBurbage ', 'MillicentBulstrode ', 'LavenderBrown ',
'TerryBoot ', 'SusanBones ', 'AmeliaBones ', 'SiriusBlack ',
'PhineasNigellus Black ', 'CuthbertBinns ', 'KatieBell ', 'BathildaBagshot ',
'LudoBagman ', 'HannahAbbott','Aragog', 'Bane', 'Beedle the Bard', 'The Bloody Baron', 'Bogrod', 'Buckbeak',
'Sir Cadogan', 'Crookshanks', 'Dobby', 'Errol', 'Fang', 'The Fat Friar',
'The Fat Lady', 'Fawkes', 'Firenze', 'Fluffy', 'Gornuk', 'Grawp', 'Griphook',
'Hedwig', 'Hokey', 'Kreacher', 'Magorian', 'Great Aunt Muriel', 'Nagini',
'Sir Nicholas de Mimsy-Porpington', 'Norbert/Norberta', 'Peeves', 'Pigwidgeon',
'Madam Rosmerta', 'Ronan', 'Scabbers', 'Scabior', 'Travers', 'Trevor', 'Winky'],
	backUpArray: [],
	easyArray: [],
	easyBackUpArray: [],
};
for (i = 0; i < harryPotter.array.length; i++) {
	harryPotter.easyArray.push(harryPotter.array[i]);
}
