var marvel = {
	name: 'Marvel',
	array: ['X-23', 'A-Bomb', 'A.I.M.', 'Aaron Stack', 'Abomination',
		'Absorbing Man', 'Abyss', 'Adam Destine', 'Adam Warlock', 'Aegis',
		'Agent Brand', 'Agent X', 'Agent Zero', 'Agents of Atlas', 'Aginar',
		'Air-Walker', 'Ajak', 'Ajaxis', 'Akemi', 'Alain', 'Albert Cleary', 'Albion',
		'Alex Power', 'Alex Wilder', 'Alexa Mendez', 'Alexander Pierce', 'Alice',
		'Alicia Masters', 'Alpha Flight', 'Alvin Maker', 'Amadeus Cho',
		'Amanda Sefton', 'Amazoness', 'American Eagle', 'Amiko', 'Amora',
		'Amphibian', 'Amun', 'Ancient One', 'Angel (Thomas Halloway)', 'Angela',
		'Anita Blake', 'Anne Marie Hoag', 'Annihilus', 'Anole', 'Ant-Man',
		'Ant-Man (Eric O\'Grady)', 'Anthem', 'Apocalypse', 'Aqueduct', 'Arachne',
		'Araña', 'Arcade', 'Arcana', 'Arclight', 'Ares', 'Argent', 'Armadillo',
		'Armor', 'Armory', 'Arnim Zola', 'Arsenic', 'Artiee', 'Asgardian',
		'Askew-Tronics', 'Asylum', 'Atlas', 'Aurora', 'Avalanche', 'Avengers',
		'Azazel', 'Angel', 'Bakuto', 'Banshee', 'Baron Strucker', 'Baron Zemo',
		'Baroness S\'Bak', 'Barracuda', 'Bart Rozum', 'Bastion',
		'Batroc the Leaper', 'Battering Ram', 'Beak', 'Becatron', 'Bedlam', 'Beef',
		'Beetle', 'Ben Grimm', 'Ben Parker', 'Ben Reilly', 'Ben Urich', 'Bengal',
		'Beta-Ray Bill', 'Betty Brant', 'Betty Ross', 'Beyonder', 'Bi-Beast',
		'Big Bertha', 'Big Wheel', 'Bill Hollister', 'Bishop', 'Black Bird',
		'Black Bolt', 'Black Cat', 'Black Crow', 'Black Knight', 'Black Mariah',
		'Black Panther', 'Black Panther (Ultimate)', 'Black Queen',
		'Black Tarantula', 'Black Tom', 'Black Widow', 'Blackheart', 'Blacklash',
		'Blackout', 'Blade', 'Blastaar', 'Blazing Skull', 'Blindfold', 'Blink',
		'Blizzard', 'Blob', 'Blockbuster', 'Blok', 'Bloke', 'Blonde Phantom',
		'Bloodaxe', 'Bloodscream', 'Bloodstorm', 'Bloodstrike', 'Blue Blade',
		'Blue Marvel', 'Blue Shield', 'Blur', 'Bob,Agent of Hydra', 'Boom Boom',
		'Boomerang', 'Box', 'Bride of Nine Spiders', 'Bromley', 'Brood',
		'Brother Voodoo', 'Brotherhood of Evil Mutants', 'Brotherhood of Mutants',
		'Bruce Banner', 'Brute', 'Bucky', 'Bug', 'Bulldozer', 'Bullseye',
		'Bushmaster', 'Bushwacker', 'Butterfly', 'Beast', 'Cable', 'Calamity',
		'Caliban', 'Callisto', 'Calypso', 'Cammi', 'Cannonball', 'Cap\'n Oz',
		'Captain America', 'Captain America (Sam Wilson)', 'Captain Britain',
		'Captain Cross', 'Captain Flint', 'Captain Marvel',
		'Captain Marvel (Mar-Vell)', 'Captain Midlands', 'Captain Stacy',
		'Captain Universe', 'Cardiac', 'Caretaker', 'Cargill', 'Carlie Cooper',
		'Carmella Unuscione', 'Carnage', 'Carol Danvers', 'Carol Hines',
		'Cassandra Nova', 'Catseye', 'Cecilia Reyes', 'Celestials', 'Centennial',
		'Centurions', 'Cerebro', 'Cerise', 'Ch\'od', 'Chamber', 'Chameleon',
		'Champions', 'Changeling', 'Charles Xavier', 'Charlie Campion',
		'Chase Stein', 'Chat', 'Chimera', 'Christian Walker', 'Chronomancer',
		'ClanDestine', 'Clea', 'Clint Barton', 'Cloak', 'Cloud 9', 'Cobalt Man',
		'Colleen Wing', 'Colonel America', 'Confederates of the Curious',
		'Constrictor', 'Contessa', 'Controller', 'Cornelius', 'Corsair', 'Cosmo',
		'Cottonmouth', 'Count Nefaria', 'Countess', 'Crimson Crusader',
		'Crimson Dynamo', 'Crimson King', 'Crossbones', 'Crule', 'Crusher Hogan',
		'Crystal', 'Cuckoo', 'Curt Conners', 'Cuthbert', 'Cyber', 'Cypher',
		'Cyclops', 'Colossus', 'Dust', 'Dum Dum Dugan', 'Druig',
		'Dreaming Celestial', 'Dreamer', 'Dreadnoughts', 'Drax', 'Dragon Man',
		'Dragon Lord', 'Dracula', 'Dr. Doom', 'Dormammu', 'Dorian Gray', 'Doorman',
		'Doop', 'Doomsday Man', 'Donald Blake', 'Domino', 'Dog Brother #1',
		'Doctor Strange', 'Doctor Spectrum', 'Doctor Octopus', 'Doctor Faustus',
		'Doc Samson', 'Dirk Anger', 'Dinah Soar', 'Diamondback', 'Diablo',
		'Dexter Bennett', 'Devos', 'Devil Dinosaur', 'Deviants', 'Detective Soap',
		'Destiny', 'Demogoblin', 'Defenders', 'Deena Pilgrim', 'Debrii',
		'Debra Whitman', 'Deathstrike', 'Deathlok', 'Deathcry', 'Deathbird',
		'Death', 'Deadpool', 'Dead Girl', 'Deacon Frost', 'Dazzler', 'Darwin',
		'Darkstar', 'Darkhawk', 'Dark X-Men', 'Dark Phoenix', 'Dark Beast',
		'Dark Avengers', 'Dargo Ktor', 'Daredevil', 'Danny Rand', 'Dani Moonstar',
		'Damage Control', 'Dakota North', 'Daken', 'Daimon Hellstrom',
		'Daily Bugle', 'Dagger', 'D\'Ken Neramani', 'Earthquake', 'Echo', 'Eclipse',
		'Eddie Brock', 'Eddie Lau', 'Edward "Ted" Forrester', 'Edwin Jarvis', 'Ego',
		'Electro', 'Elektra', 'Elements of Doom', 'Elite', 'Elixir', 'Elloe Kaifi',
		'Elsa Bloodstone', 'Empath', 'Emplate', 'Enchantress', 'Ender Wiggin',
		'Energizer', 'Epoch', 'Erik the Red', 'Eternals', 'Eternity', 'Excalibur',
		'Exiles', 'Exodus', 'Expediter', 'Ezekiel', 'Ezekiel Stane', 'Emma Frost',
		'Frog-Man', 'Frog Thor', 'Frightful Four', 'Freak', 'Franklin Storm',
		'Franklin Richards', 'Frankenstein\'s Monster', 'Frank Castle',
		'Forgotten One', 'Forge', 'Forearm', 'Force Works', 'Foggy Nelson',
		'Flying Dutchman', 'Flatman', 'Fixer', 'Firestar', 'Firelord', 'Firedrake',
		'Firebrand', 'Firebird', 'Fin Fang Foom', 'Feral', 'Fenris',
		'Felicia Hardy', 'Fat Cobra', 'Fantomex', 'Fantastic Four', 'Famine',
		'Fallen One', 'Falcon', 'Fabian Cortez', 'Gabe Jones', 'Galactus', 'Galia',
		'Gamma Corps', 'Gamora', 'Gargoyle', 'Garia', 'Garrison Kane', 'Gateway',
		'Gauntlet', 'Geiger', 'Gene Sailors', 'Generation X', 'Genesis',
		'Genis-Vell', 'George Stacy', 'Gertrude Yorkes', 'Ghost Rider',
		'Giant Girl', 'Giant Man', 'Giant-dok', 'Giant-Man', 'Gideon',
		'Git Hoskins', 'Gladiator', 'Glenn Talbot', 'Glorian', 'Goblin Queen',
		'Golden Guardian', 'Goliath', 'Gorgon', 'Gorilla Man', 'Grandmaster',
		'Gravity', 'Great Lakes Avengers', 'Green Goblin', 'Gressill',
		'Grey Gargoyle', 'Greymalkin', 'Grim Reaper', 'Groot', 'Guardian',
		'Guardians of the Galaxy', 'Guardsmen', 'Gunslinger', 'GW Bridge',
		'Gwen Stacy', 'Gambit', 'Hypno-Hustler', 'Hyperion', 'Hydro-Man', 'Hydra',
		'Hussar', 'Husk', 'Humbug', 'Human Torch (Jim Hammond)', 'Human Torch',
		'Human Robot', 'Human Fly', 'Human Cannonball', 'Hulkling', 'Hulk-dok',
		'Hulk', 'Howard The Duck', 'Howard Saint', 'Hope', 'Holy', 'Holocaust',
		'Hobgoblin', 'Hitomi Sakuma', 'Hitman', 'Hiroim', 'Hindsight Lad',
		'High Evolutionary', 'Hex', 'Heroes For Hire', 'Hercules', 'Hepzibah',
		'Henry Peter Gyrich', 'Hemingway', 'Hellions', 'Hellion', 'Hellfire Club',
		'Hellcat', 'Hela', 'Heimdall', 'Hedge Knight', 'Hawkeye (Kate Bishop)',
		'Hawkeye', 'Havok', 'Hate-Monger', 'Harry Osborn', 'Harrier', 'Harpoon',
		'Harold Meachum', 'Harley Davidson Cooper', 'Hardball', 'Happy Hogan',
		'Hannibal King', 'Hank Pym', 'Hammerhead', 'Half-Life', 'Hairball',
		'H.E.R.B.I.E.', 'H.A.M.M.E.R.', 'Ironclad', 'Iron Monger', 'Iron Man',
		'Iron Lad', 'Iron Fist (Wu Ao-Shi)', 'Iron Fist (Quan Yaozu)',
		'Iron Fist (Orson Randall)', 'Iron Fist (Bei Bang-Wen)', 'Iron Fist',
		'Iron Cross Army', 'Invisible Woman', 'Invaders', 'Ink', 'Inhumans',
		'Infant Terrible', 'Inertia', 'In-Betweener', 'Impossible Man',
		'Imperial Guard', 'Imperfects', 'Imp', 'Ilyana Rasputin', 'Illuminati',
		'Ikaris', 'Iceman', 'J. Jonah Jameson', 'Jack Flag', 'Jack Murdock',
		'Jack O\' Lantern', 'Jack Power', 'Jackal', 'Jackpot',
		'James Buchanan Barnes', 'James Howlett', 'Jamie Braddock', 'Jane Foster',
		'Janus,the Nega-Man', 'Jasper Sitwell', 'Jazinda', 'Jemma Simmons',
		'Jennifer Smith', 'Jeryn Hogarth', 'Jessica Drew', 'Jessica Jones',
		'Jetstream', 'Jigsaw', 'Jimmy Woo', 'Joan the Mouse', 'Jocasta',
		'John Farson', 'John Jameson', 'John Porter', 'John Wraith', 'Johnny Blaze',
		'Johnny Storm', 'Joseph', 'Joshua Kane', 'Josiah X', 'Joy Meachum',
		'Joystick', 'Juggernaut', 'Jule Carpenter', 'Julia Carpenter',
		'Julian Keller', 'Junta', 'Justice', 'Justin Hammer', 'Jubilee',
		'Jean Grey', 'Kylun', 'Kulan Gath', 'Kronos', 'Krista Starr', 'Kree',
		'Kraven the Hunter', 'Korvac', 'Korg', 'Korath', 'Komodo', 'Klaw',
		'Kitty Pryde', 'Kinsey Walden', 'Kingpin', 'King Cobra', 'Killraven',
		'Killmonger', 'Killer Shrike', 'Kid Colt', 'Khan', 'Ken Ellis',
		'Katie Power', 'Kate Bishop', 'Kat Farrell', 'Karolina Dean', 'Karnak',
		'Karma', 'Karen Page', 'Karen O\'Malley', 'Kang', 'Kabuki', 'Ka-Zar',
		'Lyja', 'Luminals', 'Luke Cage', 'Lucy in the Sky', 'Lucky Pierre',
		'Luckman', 'Lorna Dane', 'Lords of Avalon', 'Lord Tyger', 'Lord Hawal',
		'Longshot', 'Loners', 'Loki', 'Logan', 'Lockjaw', 'Lockheed', 'Loa',
		'Lizard', 'Liz Osborn', 'Living Tribunal', 'Living Mummy',
		'Living Lightning', 'Lionheart', 'Lily Hollister', 'Lilith', 'Lilandra',
		'Lila Cheney', 'Lightspeed', 'Lightning Lords of Nepal', 'Lifeguard',
		'Lieutenant Marcus Stone', 'Lethal Legion', 'Lester', 'Leper Queen',
		'Leopardon', 'Leo Fitz', 'Leo', 'Lenny Balinger', 'The Thunderer','Lei Kung', 'Legion', 'Leech', 'Leader', 'Layla Miller', 'Lava-Man', 'Landau',
		'Lance Hunter', 'Lake', 'Lady Vermin', 'Lady Ursula', 'Lady Mastermind',
		'Lady Deathstrike', 'Lady Bullseye', 'La Nuit', 'Mystique', 'Mysterio',
		'MVP', 'Multiple Man', 'Mulholland Black', 'MS2',
		'Ms. Marvel (Kamala Khan)', 'Mr. X', 'Mr. Payback', 'Mr. Negative',
		'Mr. Meugniot', 'Mr. Immortal', 'Mr. Hyde', 'Mr. Fixit', 'Mr. Fish',
		'Mr. Fantastic', 'Mr. Bumpo', 'Mother Askani', 'Morph', 'Morlun',
		'Morlocks', 'Morgan Stark', 'Morg', 'Mordo', 'Morbius', 'Moonstone',
		'Moondragon', 'Moon Knight', 'Moon Girl', 'Monster Badoon', 'Mongu',
		'Mongoose', 'Molten Man', 'Molly Von Richtofen', 'Molly Hayes',
		'Molecule Man', 'Mole Man', 'Mojo', 'Moira MacTaggert', 'Mockingbird',
		'Misty Knight', 'Mister Sinister', 'Mister Fear', 'Miss America',
		'Miracleman', 'Mindworm', 'Mimic', 'Millie the Model', 'Millenium Guard',
		'Mikhail Rasputin', 'Miek', 'Midnight', 'Micromax', 'Microchip', 'Microbe',
		'Micro/Macro', 'MI: 13', 'Meteorite', 'Metal Master', 'Mesmero', 'Mercury',
		'Mephistopheles', 'Mephisto', 'Mentor', 'Mentallo', 'Menace', 'Meltdown',
		'Melinda May', 'Meggan', 'Medusa', 'May Parker', 'Maximus', 'Maverick',
		'Mauler', 'Mattie Franklin', 'Matthew Murdock', 'Matsu\'o Tsurayaba',
		'Mathemanic', 'Masters of Evil', 'Mastermind', 'Master Mold',
		'Master Chief', 'Masque', 'Masked Marvel', 'Mary Jane Watson', 'Marvex',
		'Marvel Zombies', 'Marvel Boy', 'Marvel Apes', 'Martin Li',
		'Marten Broadcloak', 'Marrow', 'Mariko Yashida', 'Maria Hill',
		'Marcus Van Sciver', 'Marauders', 'Mantis', 'Manta', 'Mandroid', 'Mandrill',
		'Mandarin', 'Man-Wolf', 'Man-Thing', 'Malice', 'Malcom Powder',
		'Malcolm Colcord', 'Makkari', 'Major Mapleleaf', 'Magus', 'Magneto',
		'Magma', 'Maginty', 'Magik', 'Maggott', 'Magdalene', 'Maestro', 'Maelstrom',
		'Madrox', 'Madripoor', 'Madelyne Pryor', 'Maddog', 'Madame Masque',
		'Madame Hydra', 'Mad Thinker', 'Machine Man', 'Mach IV', 'Mac Gargan',
		'Ma Gnuci', 'M.O.D.O.K.', 'M.O.D.O.G.', 'M.O.D.A.M.', 'M', 'Nuke',
		'Nova (Frankie Raye)', 'Nova', 'Northstar', 'Norrin Radd',
		'Norman Osborn (Green Goblin)', 'Nomad', 'Nocturne', 'Nitro',
		'Nine-Fold Daughters of Xao', 'Nightshade', 'Nightmare', 'Nighthawk',
		'Nightcrawler', 'Night Thrasher', 'Night Nurse', 'Nicolaos', 'Nico Minoru',
		'Nick Fury', 'Nextwave', 'Next Avengers', 'Newton Destine', 'New X-Men',
		'New Warriors', 'New Mutants', 'New Goblin', 'Network', 'Nemesis', 'Nekra',
		'Nehzno', 'Nebula', 'Natasha Romanoff', 'Naoko', 'Namorita', 'Namora',
		'Namor', 'Nakia', 'Ozymandias', 'Owl', 'Overlord', 'Outlaw Kid',
		'Otto Octavius', 'Orphan-Maker', 'Orphan', 'Ord', 'Oracle', 'Onslaught',
		'Omega the Unknown', 'Omega Sentinel', 'Omega Red', 'Omega Flight',
		'Old Lace', 'Okoye', 'Ogun', 'Odin', 'Obadiah Stane', 'Pyro', 'Purple Man',
		'Purifiers', 'Puppet Master', 'Punisher (2099)', 'Punisher', 'Puma', 'pug',
		'Puff Adder', 'Puck', 'PsyNapse', 'Psylocke', 'Psycho-Man', 'Prowler',
		'Proudstar', 'Proteus', 'Professor X', 'Professor Monster', 'Professor',
		'Proemial Gods', 'Prodigy', 'Prism', 'Princess Powerful',
		'Prince of Orphans', 'Prima', 'Pride', 'Pretty Boy', 'Preak', 'Praxagora',
		'Power Pack', 'Power Man', 'Post', 'Polaris', 'Plazm', 'Pixie', 'Pip',
		'Piledriver', 'Phyla-Vell', 'Photon', 'Phil Sheldon', 'Phil Coulson',
		'Phantom Reporter', 'Phalanx', 'Peter Quill', 'Peter Parker', 'Pete Wisdom',
		'Pet Avengers', 'Pestilence', 'Pepper Potts', 'Penance', 'Payback',
		'Patriot', 'Patch', 'Paper Doll', 'Pandemic', 'Paladin', 'Paibok',
		'Quicksilver', 'Quentin Quire', 'Queen Noir', 'Quasimodo', 'Quasar',
		'Quake', 'Russian', 'Runaways', 'Rumiko Fujikawa', 'Roxanne Simpson',
		'Roulette', 'Roughhouse', 'Ronan', 'Romulus', 'Roland Deschain',
		'Rogue (Deadpool)', 'Rogue', 'Rockslide', 'Rocket Racer', 'Rocket Raccoon',
		'Robin Chapel', 'Robert Baldwin', 'Robbie Robertson', 'Risque', 'Riptide',
		'Rictor', 'Ricochet', 'Rick Jones', 'Richard Fisk', 'Rhomann Dey', 'Rhodey',
		'Rhino', 'Revanche', 'Retro Girl', 'Reptil', 'Redwing', 'Red Wolf',
		'Red Skull', 'Red Shift', 'Red She-Hulk', 'Red Hulk', 'Red Ghost', 'Red 9',
		'Reavers', 'Reaper', 'Raza', 'Rawhide Kid', 'Ravenous', 'Rattler', 'Random',
		'Randall Flagg', 'Randall', 'Raider', 'Rage', 'Rafael Vega',
		'Radioactive Man', 'Rachel Grey', 'Synch', 'Sym', 'Swordsman', 'Switch',
		'Sway', 'Swarm', 'Susan Delgado', 'Surge', 'Supreme Intelligence',
		'Supernaut', 'Super-Skrull', 'Super-Adaptoid', 'Super Hero Squad',
		'Sunspot', 'Sunset Bain', 'Sunfire', 'Sumo', 'Sugar Man', 'Sue Storm',
		'Stryfe', 'Strong Guy', 'Stranger', 'Storm', 'Stone Men', 'Stingray',
		'Stilt-Man', 'Stick', 'Steve Rogers', 'Stephen Strange',
		'Stephanie de la Spiroza', 'Stepford Cuckoos', 'Stellaris', 'Steel Serpent',
		'Stature', 'Stark Industries', 'Starjammers', 'Starhawk', 'Starfox',
		'Stardust', 'Starbolt', 'Star-Lord', 'Star Brand', 'Stacy X',
		'Squirrel Girl', 'Squadron Supreme', 'Squadron Sinister', 'Spyke', 'Sprite',
		'Spot', 'Spitfire', 'Spirit', 'Spiral', 'Spider-Woman (Mattie Franklin)',
		'Spider-Woman (Charlotte Witter)', 'Spider-Woman', 'Spider-Man (Noir)',
		'Spider-Man (Miles Morales)', 'Spider-Man (Ben Reilly)',
		'Spider-Man (Ai Apaec)', 'Spider-Man (2099)', 'Spider-Man (1602)',
		'Spider-Man', 'Spider-Ham', 'Spider-Gwen', 'Spider-Girl', 'Spider-dok',
		'Sphinx', 'Spencer Smythe', 'Speedball', 'Speed Demon', 'Speed', 'Spectrum',
		'Spacker Dave', 'Sons of the Tiger', 'Songbird', 'Solo', 'Snowbird',
		'Smiling Tiger', 'Smasher', 'Slyde', 'Slipstream', 'Sleepwalker', 'Sleeper',
		'Slayback', 'Slapstick', 'Skullbuster', 'Skrulls', 'Skreet', 'Skin',
		'Skaar', 'Sister Grimm', 'Siren', 'Sir Ram', 'Sinister Six', 'Sin',
		'Silvermane', 'Silverclaw', 'Silver Surfer', 'Silver Samurai',
		'Silver Sable', 'Silver Fox', 'Silver Centurion', 'Silk Fever',
		'Silhouette', 'Sif', 'Shuri', 'Shriek', 'Shotgun', 'Shooting Star',
		'Shockwave', 'Shocker', 'Shiver Man', 'Shiva', 'Shinobi Shaw',
		'Shinko Yamashiro', 'Shi\'Ar', 'Sheva Callister', 'Shen',
		'She-Hulk (Ultimate)', 'She-Hulk (Lyra)', 'She-Hulk', 'Shatterstar',
		'Sharon Ventura', 'Sharon Carter', 'Shard', 'Shape', 'Shanna the She-Devil',
		'Shang-Chi', 'Shane Yamada-Jones', 'Shaman', 'Shalla-bal',
		'Shadu the Shady', 'Shadowcat', 'Shadow King', 'Shades', 'Sersi',
		'Serpent Society', 'Ser Duncan', 'Sentry', 'Sentinels', 'Sentinel',
		'Senator Kelly', 'Selene', 'Secret Warriors', 'Sebastian Shaw', 'Screwball',
		'Scream', 'Scrambler', 'Scourge', 'Scorpion', 'Scarlet Witch',
		'Scarlet Spider', 'Scarecrow', 'Scalphunter', 'Sauron', 'Satana',
		'Sasquatch', 'Saracen', 'Santa Claus', 'Sandman', 'Salo', 'Sally Floyd',
		'Salem\'s Seven', 'Sage', 'Sabretooth', 'Sabra', 'S.H.I.E.L.D.',
		'The Spike', 'The Shiver Man', 'The Santerians', 'The Renegades',
		'The Phantom', 'The Order', 'The Liberty Legion', 'The Liberteens',
		'The Leader', 'The Initiative', 'The Hunter', 'The Howling Commandos',
		'The Hood', 'The Hand', 'The Fury', 'The Fallen', 'The Executioner',
		'The Enforcers', 'The Collector', 'The Captain', 'The Call',
		'The Anarchist', 'The 198', 'Thanos', 'Thaddeus Ross', 'Texas Twister',
		'Terror', 'Terrax', 'Tenebrous', 'Tempest', 'Ted Forrester', 'Tattoo',
		'Taskmaster', 'Tarot', 'Tarantula', 'Tana Nile', 'Talos', 'Talon',
		'Talkback', 'Talisman', 'Tag', 'T\'Challa', 'Unus', 'Union Jack', 'Unicorn',
		'Umar', 'Ultron', 'Ultragirl', 'Ultra-Adaptoid', 'Ultimo', 'Ultimatum',
		'Ultimates', 'Ulik', 'Uatu The Watcher', 'U.S. Agent', 'U-Go Girl',
		'U-Foes', 'Vulture', 'Vulcan', 'Vivisector', 'Vision', 'Virginia Dare',
		'Viper', 'Violations', 'Vindicator', 'Vin Gonzales', 'Victor Von Doom',
		'Victor Mancha', 'Vertigo', 'Vermin', 'Venus Dee Milo', 'Venus',
		'Venom (Ultimate)', 'Venom (Mac Gargan)', 'Venom', 'Vengeance', 'Veda',
		'Vector', 'Vargas', 'Vapor', 'Vanisher', 'Vance Astro', 'Vampiro',
		'Valkyrie', 'Valeria Richards', 'Wrecking Crew', 'Wrecker', 'Wraith',
		'Wong', 'Wonder Man', 'Wolverine X-23', 'Wolverine', 'Wolver-dok',
		'Wolfsbane', 'Wolfpack', 'Wolf Cub', 'Wither', 'Winter Soldier',
		'Wind Dancer', 'Wilson Fisk', 'William Stryker', 'Wildside', 'Wild Pack',
		'Wild Child', 'Wiccan', 'Whizzer', 'White Tiger', 'White Queen', 'Whistler',
		'Whirlwind', 'Whiplash', 'Werewolf By Night', 'Wendigo', 'Wendell Vaughn',
		'Wendell Rand', 'Weapon X', 'Weapon Omega', 'Wasp', 'Warstar',
		'Warren Worthington III', 'Warpath', 'Warlock', 'Warhawk', 'Ward Meachum',
		'Warbound', 'Warbird', 'War Machine James Rhodes', 'War Machine', 'War',
		'Wallow', 'Wallop', 'Wallflower', 'Xorn', 'Xavin', 'X.S.E.', 'X-Statix',
		'X-Ray', 'X-Men', 'X-Man', 'X-Force', 'X-Cutioner', 'X-Babies', 'X-51',
		'Young X-Men', 'Young Avengers', 'Yondu', 'Yo-Yo', 'Yellowjacket',
		'Yellow Claw', 'Zzzax', 'Zuras', 'Zombie', 'Zodiak', 'Zemo', 'Zeigeist',
		'Zarek', 'Zarda', 'Zaran', 'Zaladane',
	],
	backUpArray: [],
	easyArray: [],
	easyBackUpArray: [],
};
for (i = 0; i < marvel.array.length; i++) {
	marvel.easyArray.push(marvel.array[i]);
}
